"""
    
    Personal engine built on Pygame and ECS.

    This file is a part of the lucid-engine
    project and distributed under MIT license.
    https://github.com/kadir014/lucid-engine

"""

import os
from pathlib import Path
import argparse
import re


README_TEMPLATE = """
# {project}
{desc} - {version}

Created with Lucid Engine!

# Running
```shell
$ uv run {project}_main
```
"""

PYPROJECT_TEMPLATE = """
[project]
name = "{project}"
description = "{desc}"
version = "{version}"
readme = "README.md"
classifiers = [
    "Topic :: Games/Entertainment",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "pygame-ce",
    "lucid-engine",
]
requires-python = ">=3.12"

[project.scripts]
{project}_main = "{project}.__main__:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
""".strip()

MAIN_TEMPLATE = """
\"\"\"
This file is autogenerated using Lucid Engine.

main.py
=========
This is the entry point to that creates and runs the Lucid application instance.
\"\"\"

import lucid

from {project} import shared
from {project}.scenes.game import Game


def main() -> None:
    app = lucid.App(shared)
    shared.app = app

    app.add_scene(Game)

    app.scene = "Game"

    app.run()


if __name__ == "__main__":
    main()
""".strip()

SCENE_TEMPLATE = """
\"\"\"
This file is autogenerated using Lucid Engine.

scene/game.py
=============
Scenes represent individual states of the application, such as
menus, gameplay, or loading screens. This example provides a
starting point for your own scene implementation.
\"\"\"

import lucid

from {project} import shared


class Game(lucid.Scene):
    def __init__(self) -> None:
        super().__init__()

        self.font = shared.assets.font("Arial", 20)

    def activated(self) -> None:
        print("Game scene has started!")

    def update(self) -> None:
        if shared.input.key_pressed("escape"):
            shared.app.stop()

    def render_before(self) -> None:
        text_surf = self.font.render(
            "There supposed to be a game here.",
            True,
            (255, 255, 255)
        )
        shared.app.display.blit(
            text_surf,
            (
                shared.app.window_center.x - text_surf.get_width() * 0.5,
                shared.app.window_center.y - text_surf.get_height() * 0.5
            )
        )
""".strip()

SHARED_TEMPLATE = """
\"\"\"
This file is autogenerated using Lucid Engine.

shared.py
=========
This module contains global objects and services that are shared
throughout the application and persist for its entire lifetime.
\"\"\"

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from lucid.core import App
    from lucid.asset import AssetManager
    from lucid.input import InputManager

from lucid.models import AppConfig, VSyncMode


# This must exist for the application to initialize.
INITIAL_CONFIG = AppConfig(
    window_size=(1280, 720),
    vsync=VSyncMode.CONSTANT
)

# These services will be automatically assigned by the application instance!
app: "App | None" = None
assets: "AssetManager | None" = None
input: "InputManager | None" = None
"""


def mkdir(path: Path) -> None:
    """
    Create directory if not exists.
    
    Parameters
    ----------
    path
        Path to directory
    """

    if os.path.exists(path):
        return
    
    os.mkdir(path)
    print(f"Succesfully created '{path.absolute()}'")


def write(path: Path, content: str, overwrite: bool = False) -> None:
    """
    Create & write to a file.

    Parameters
    ----------
    path
        Path to file
    content
        Content to write
    overwrite
        Overwrite existing file?
    """

    if not overwrite and os.path.exists(path):
        return
    
    with open(path, "w", encoding="utf-8") as file:
        file.write(content)
        print(f"Succesfully wrote to '{path.absolute()}'")


def normalize_identifier(name: str) -> str:
    """ Normalize a string into valid Python identifier. """

    name = name.lower().strip()
    name = re.sub(r"[^a-z0-9_]", "_", name)
    if re.match(r"^\d", name):
        name = "_" + name
    return name


def init() -> None:
    """
    Initialize a template Lucid Engine project.
    """

    parser = argparse.ArgumentParser(
        prog="init",
        description="Initialize a Lucid Engine project"
    )

    parser.add_argument(
        "--overwrite",
        help="Overwrite existing files.",
        action="store_true"
    )

    args = parser.parse_args()

    BASE = Path.cwd()
    DESCRIPTION = "Game project with Lucid Engine"
    VERSION = "0.0.1"

    project_name = normalize_identifier(BASE.name)

    pyproject = PYPROJECT_TEMPLATE.format(
        project=project_name,
        desc=DESCRIPTION,
        version=VERSION
    )
    write(BASE / "pyproject.toml", pyproject, args.overwrite)

    readme = README_TEMPLATE.format(
        project=project_name,
        desc=DESCRIPTION,
        version=VERSION
    )
    write(BASE / "README.md", readme, args.overwrite)

    mkdir(BASE / "src")
    mkdir(BASE / "src" / project_name)
    mkdir(BASE / "src" / project_name / "scenes")

    main = MAIN_TEMPLATE.format(project=project_name)
    write(BASE / "src" / project_name / "__main__.py", main, args.overwrite)

    scene = SCENE_TEMPLATE.format(project=project_name)
    write(BASE / "src" / project_name / "scenes" / "game.py", scene, args.overwrite)

    shared = SHARED_TEMPLATE
    write(BASE / "src" / project_name / "shared.py", shared, args.overwrite)

    cmd = f"$ uv run {project_name}_main"
    print(
        "\n"
        f"··───────··\n"
        "\n"
        "Your template project using Lucid Engine is all set up!\n"
        "\n"
        "You can run your app using:\n"
        f"╭─{'─'*len(cmd)}─╮\n"
        f"│ {cmd} │\n"
        f"╰─{'─'*len(cmd)}─╯\n"
        "\n"
        "Or you can change the entry script name in pyproject.toml file.\n"
        "Have fun developing! 😊"
    )


if __name__ == "__main__":
    init()