"""
This file is autogenerated using Lucid Engine.

main.py
=========
This is the entry point to that creates and runs the Lucid application instance.
"""

from lucid.core import App

from {project} import shared
from {project}.scenes.game import Game


def main() -> None:
    app = App(shared)
    shared.app = app

    app.add_scene(Game)

    app.scene = "Game"

    app.run()


if __name__ == "__main__":
    main()
