"""
This file is autogenerated using Lucid Engine.

scene/game.py
=============
Scenes represent individual states of the application, such as
menus, gameplay, or loading screens. This example provides a
starting point for your own scene implementation.
"""

from lucid.core import Scene

from {project} import shared


class Game(Scene):
    def __init__(self) -> None:
        super().__init__()

        self.font = shared.assets.font("Arial", 20)

    def activated(self, previous) -> None:
        print("Game scene has started!")

    def update(self) -> None:
        if shared.input.key_pressed("escape"):
            shared.app.stop()

    def render_before(self) -> None:
        text_surf = self.font.render(
            "There supposed to be a game here.",
            True,
            (255, 255, 255)
        )
        shared.app.display.blit(
            text_surf,
            (
                shared.app.window_center.x - text_surf.get_width() * 0.5,
                shared.app.window_center.y - text_surf.get_height() * 0.5
            )
        )
