"""
This file is autogenerated using Lucid Engine.

shared.py
=========
This module contains global objects and services that are shared
throughout the application and persist for its entire lifetime.
"""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from lucid.core import App
    from lucid.asset import AssetManager
    from lucid.input import InputManager

from lucid.models import AppConfig, VSyncMode


# This must exist for the application to initialize.
INITIAL_CONFIG = AppConfig(
    window_size=(1280, 720),
    vsync=VSyncMode.CONSTANT
)

# These services will be automatically assigned by the application instance!
app: "App | None" = None
assets: "AssetManager | None" = None
input: "InputManager | None" = None
